/**
 * OpenGD77 CPS CSV exporter for Radiomap repeater data.
 * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
 * Format: OpenGD77 CPS channel import CSV — with header row, 28 columns per row.
 * Columns: Channel Number,Channel Name,Channel Type,Rx Frequency,Tx Frequency,Bandwidth (kHz),Colour Code,Timeslot,Contact,TG List,DMR ID,TS1_TA_Tx,TS2_TA_Tx ID,RX Tone,TX Tone,Squelch,Power,Rx Only,Zone Skip,All Skip,TOT,VOX,No Beep,No Eco,APRS,Latitude,Longitude,Use Location
 *
 * Supports both Analogue and Digital (DMR) channels.
 * DMR fields used: r.color (Colour Code), r.slot (Timeslot).
 *
 * Exposes:
 *   exportOpenGD77(rows, criteria)  — triggers browser download
 *   buildOpenGD77Filename(criteria) — returns filename string
 */

function buildOpenGD77Filename(criteria) {
  var date = new Date().toISOString().slice(0, 10);
  var parts = ['radiomap', 'opengd77'];
  var sanitize = function (s) {
    return String(s).replace(/\s+/g, '-').replace(/[^a-zA-Z0-9\-\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1]/g, '').toLowerCase().slice(0, 30);
  };
  if (criteria) {
    if (criteria.context === 'neighbors') {
      parts.push('nodos-cercanos');
      if (criteria.signal) parts.push(sanitize(criteria.signal));
    }
    if (criteria.nearMe) parts.push('cerca-de-mi');
    var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
    bandas.forEach(function (b) { if (b) parts.push(String(b).toLowerCase()); });
    var types = criteria.types || [];
    if (types.indexOf('echolink') >= 0) parts.push('echolink');
    if (types.indexOf('dmr') >= 0) parts.push('dmr');
    if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
    if (types.indexOf('atc') >= 0) parts.push('atc');
    if (types.indexOf('fire') >= 0) parts.push('bomberos');
    if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
    if (types.indexOf('sea') >= 0) parts.push('maritimo');
    var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
    conferences.forEach(function (c) { if (c) parts.push('conferencia-' + sanitize(c)); });
    var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
    regions.forEach(function (reg) { var r = sanitize(reg); if (r) parts.push('region-' + r); });
    var search = criteria.search != null ? criteria.search : '';
    if (search && String(search).trim()) {
      var q = sanitize(String(search).trim()).slice(0, 20);
      if (q) parts.push('busqueda-' + q);
    }
  }
  parts.push(date);
  return parts.join('-') + '.csv';
}

function exportOpenGD77(rows, criteria) {
  var HEADER = 'Channel Number,Channel Name,Channel Type,Rx Frequency,Tx Frequency,Bandwidth (kHz),Colour Code,Timeslot,Contact,TG List,DMR ID,TS1_TA_Tx,TS2_TA_Tx ID,RX Tone,TX Tone,Squelch,Power,Rx Only,Zone Skip,All Skip,TOT,VOX,No Beep,No Eco,APRS,Latitude,Longitude,Use Location';

  var esc = function (v) {
    if (v == null || v === '') return '';
    var s = '' + v;
    if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\n') >= 0) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  };

  /* OpenGD77 supported bands: VHF 136-174 MHz, UHF 400-470 MHz */
  var inSupportedBand = function (f) {
    return (f >= 136 && f <= 174) || (f >= 400 && f <= 470);
  };

  /* Standard CTCSS tones (EIA) */
  var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
    100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
    146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
    218.1,225.7,233.6,241.8,250.3];

  var normalizeText = function (s) {
    return String(s)
      .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
      .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
      .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
      .toUpperCase();
  };

  var channel = 1;
  var dataRows = rows.map(function (r) {
    var rx = parseFloat(r.rx);
    var txRaw = parseFloat(r.tx);
    var rxOk = !isNaN(rx);
    var tx = !isNaN(txRaw) ? txRaw : rx;

    if (!rxOk || !inSupportedBand(rx)) return null;

    var isDMR = r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
        (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0);

    var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 16) : '';
    var fmtFreq = function (f) { return f.toFixed(5); };

    var cols;
    if (isDMR) {
      var colorCode = (r.color != null && r.color !== '') ? String(r.color) : '1';
      var timeslot = (r.slot != null && r.slot !== '') ? String(r.slot) : '1';
      cols = [
        channel++, esc(name), 'Digital',
        rxOk ? fmtFreq(rx) : '', rxOk ? fmtFreq(tx) : '',
        '', colorCode, timeslot, '', '', '',
        'Off', 'Off', '', '', '',
        'Master', 'No', 'No', 'No', '0', 'Off', 'No', 'No', '', '0', '0', 'No'
      ];
    } else {
      var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
      var tonoNum = parseFloat(tonoRaw);
      var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) { return Math.abs(t - tonoNum) < 0.05; });
      var hasTone = tonoRaw !== '' && isValidTone;
      var tone = hasTone ? tonoNum.toFixed(1) : '';
      cols = [
        channel++, esc(name), 'Analogue',
        rxOk ? fmtFreq(rx) : '', rxOk ? fmtFreq(tx) : '',
        '12.5', '', '', '', '', '',
        '', '', tone, tone, 'Disabled',
        'Master', 'No', 'No', 'No', '0', 'Off', 'No', 'No', '', '0', '0', 'No'
      ];
    }
    return cols.join(',');
  }).filter(function (line) { return line !== null; });

  var csv = [HEADER].concat(dataRows).join('\r\n');
  var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = buildOpenGD77Filename(criteria);
  a.click();
  URL.revokeObjectURL(a.href);
}
