#!/usr/bin/env python3
"""
Generates scripts/exporter/{format}/mapper.js from each reference.csv,
and scripts/exporter/registry.js listing all available exporters.

Run from repo root:
    python scripts/generate-exporter-mapper.py
"""
from __future__ import annotations

import csv
import json
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPORTER_ROOT = REPO_ROOT / "scripts" / "exporter"


def read_headers(reference_csv: Path) -> list[str]:
    with open(reference_csv, encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        return next(reader, [])


def generate_chirp_mapper(headers: list[str]) -> str:
    header_str = ",".join(headers)
    return textwrap.dedent(f"""\
        /**
         * CHIRP CSV exporter for Radiomap repeater data.
         * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
         * CHIRP columns: {header_str}
         *
         * Exposes:
         *   exportChirp(rows, criteria)  — triggers browser download of CHIRP CSV
         *   buildChirpFilename(criteria) — returns filename string
         */

        function buildChirpFilename(criteria) {{
          var date = new Date().toISOString().slice(0, 10);
          var parts = ['radiomap', 'chirp'];
          var sanitize = function (s) {{
            return String(s).replace(/\\s+/g, '-').replace(/[^a-zA-Z0-9\\-\\u00e1\\u00e9\\u00ed\\u00f3\\u00fa\\u00f1]/g, '').toLowerCase().slice(0, 30);
          }};
          if (criteria) {{
            if (criteria.context === 'neighbors') {{
              parts.push('nodos-cercanos');
              if (criteria.signal) parts.push(sanitize(criteria.signal));
            }}
            if (criteria.nearMe) parts.push('cerca-de-mi');
            var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
            bandas.forEach(function (b) {{ if (b) parts.push(String(b).toLowerCase()); }});
            var types = criteria.types || [];
            if (types.indexOf('echolink') >= 0) parts.push('echolink');
            if (types.indexOf('dmr') >= 0) parts.push('dmr');
            if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
            if (types.indexOf('atc') >= 0) parts.push('atc');
            if (types.indexOf('fire') >= 0) parts.push('bomberos');
            if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
            if (types.indexOf('sea') >= 0) parts.push('maritimo');
            var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
            conferences.forEach(function (c) {{ if (c) parts.push('conferencia-' + sanitize(c)); }});
            var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
            regions.forEach(function (reg) {{ var r = sanitize(reg); if (r) parts.push('region-' + r); }});
            var search = criteria.search != null ? criteria.search : '';
            if (search && String(search).trim()) {{
              var q = sanitize(String(search).trim()).slice(0, 20);
              if (q) parts.push('busqueda-' + q);
            }}
          }}
          parts.push(date);
          return parts.join('-') + '.csv';
        }}

        function exportChirp(rows, criteria) {{
          var HEADER = '{header_str}';

          var esc = function (v) {{
            if (v == null || v === '') return '';
            var s = '' + v;
            if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\\n') >= 0) {{
              return '"' + s.replace(/"/g, '""') + '"';
            }}
            return s;
          }};

          var mapMode = function (banda) {{
            if (!banda) return 'FM';
            var b = String(banda).toUpperCase();
            if (b.indexOf('DMR') >= 0) return 'DMR';
            if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
            return 'FM';
          }};

          var location = 1;
          var dataRows = rows.map(function (r) {{
            if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
                (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {{
              return null;
            }}

            var rx = parseFloat(r.rx);
            var tx = parseFloat(r.tx);
            var rxOk = !isNaN(rx);
            var txOk = !isNaN(tx);

            var duplex = '';
            var offset = (0).toFixed(6);
            if (rxOk && txOk) {{
              var diff = tx - rx;
              if (Math.abs(diff) > 0.0001) {{
                duplex = diff > 0 ? '+' : '-';
                offset = Math.abs(diff).toFixed(6);
              }}
            }}

            var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
            var tonoNum = parseFloat(tonoRaw);
            var hasTone = tonoRaw !== '' && !isNaN(tonoNum) && tonoNum > 0;
            var toneField = hasTone ? 'Tone' : '';
            var rToneFreq = hasTone ? tonoNum.toFixed(1) : '88.5';

            var nombre = r.nombre != null ? String(r.nombre) : '';
            var ubicacion = r.ubicacion != null ? String(r.ubicacion) : '';
            var comment = '';
            if (nombre && ubicacion) {{
              comment = (nombre + ' - ' + ubicacion).slice(0, 255);
            }} else if (nombre) {{
              comment = nombre.slice(0, 255);
            }} else if (ubicacion) {{
              comment = ubicacion.slice(0, 255);
            }}

            var name = r.signal != null ? String(r.signal).slice(0, 16) : '';

            var cols = [
              location++,
              esc(name),
              rxOk ? rx.toFixed(6) : '',
              duplex,
              offset,
              toneField,
              rToneFreq,
              rToneFreq,
              '023',
              'NN',
              '023',
              'Tone->Tone',
              mapMode(r.banda),
              '12.50',
              '',
              '1W',
              esc(comment),
              '',
              '',
              '',
              ''
            ];
            return cols.join(',');
          }}).filter(function (line) {{ return line !== null; }});

          var csv = [HEADER].concat(dataRows).join('\\r\\n');
          var blob = new Blob([csv], {{ type: 'text/csv;charset=utf-8' }});
          var a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = buildChirpFilename(criteria);
          a.click();
          URL.revokeObjectURL(a.href);
        }}
        """)


def generate_ft5dr_mapper(headers: list[str]) -> str:
    num_cols = len(headers)
    return textwrap.dedent(f"""\
        /**
         * Yaesu FT5DR ADMS CSV exporter for Radiomap repeater data.
         * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
         * Format: Yaesu ADMS-1 compatible CSV — no header row, {num_cols} columns per row.
         *
         * Column layout (inferred from reference.csv):
         *   0:channel  1:skip  2:rx_freq  3:tx_freq  4:offset(|tx-rx|)  5:OFF  6:ON
         *   7:tx_mode  8:rx_mode  9:ON  10:name  11:tone_mode  12:ctcss_freq
         *   13:dcs_code  14:dcs_polarity  15:1600Hz  16:rx_squelch  17:tx_squelch
         *   18:power  19:OFF  20:ON  21:step  22-51:feature_flags  52:empty  53:0
         *
         * Exposes:
         *   exportFT5DR(rows, criteria)  — triggers browser download
         *   buildFT5DRFilename(criteria) — returns filename string
         */

        function buildFT5DRFilename(criteria) {{
          var date = new Date().toISOString().slice(0, 10);
          var parts = ['radiomap', 'ft5dr'];
          var sanitize = function (s) {{
            return String(s).replace(/\\s+/g, '-').replace(/[^a-zA-Z0-9\\-\\u00e1\\u00e9\\u00ed\\u00f3\\u00fa\\u00f1]/g, '').toLowerCase().slice(0, 30);
          }};
          if (criteria) {{
            if (criteria.context === 'neighbors') {{
              parts.push('nodos-cercanos');
              if (criteria.signal) parts.push(sanitize(criteria.signal));
            }}
            if (criteria.nearMe) parts.push('cerca-de-mi');
            var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
            bandas.forEach(function (b) {{ if (b) parts.push(String(b).toLowerCase()); }});
            var types = criteria.types || [];
            if (types.indexOf('echolink') >= 0) parts.push('echolink');
            if (types.indexOf('dmr') >= 0) parts.push('dmr');
            if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
            if (types.indexOf('atc') >= 0) parts.push('atc');
            if (types.indexOf('fire') >= 0) parts.push('bomberos');
            if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
            if (types.indexOf('sea') >= 0) parts.push('maritimo');
            var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
            conferences.forEach(function (c) {{ if (c) parts.push('conferencia-' + sanitize(c)); }});
            var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
            regions.forEach(function (reg) {{ var r = sanitize(reg); if (r) parts.push('region-' + r); }});
            var search = criteria.search != null ? criteria.search : '';
            if (search && String(search).trim()) {{
              var q = sanitize(String(search).trim()).slice(0, 20);
              if (q) parts.push('busqueda-' + q);
            }}
          }}
          parts.push(date);
          return parts.join('-') + '.csv';
        }}

        function exportFT5DR(rows, criteria) {{
          var esc = function (v) {{
            if (v == null || v === '') return '';
            var s = '' + v;
            if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\\n') >= 0) {{
              return '"' + s.replace(/"/g, '""') + '"';
            }}
            return s;
          }};

          var mapMode = function (banda) {{
            if (!banda) return 'FM';
            var b = String(banda).toUpperCase();
            if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
            return 'FM';
          }};

          /* Yaesu FT5DR supported bands: VHF 108-174 MHz, UHF 420-470 MHz */
          var inSupportedBand = function (f) {{
            return (f >= 108 && f <= 174) || (f >= 420 && f <= 470);
          }};

          /* Standard CTCSS tones (EIA) */
          var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
            100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
            146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
            218.1,225.7,233.6,241.8,250.3];

          var flags = [];
          for (var i = 0; i < 30; i++) flags.push('OFF');

          var channel = 1;
          var dataRows = rows.map(function (r) {{
            if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
                (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {{
              return null;
            }}

            var rx = parseFloat(r.rx);
            var txRaw = parseFloat(r.tx);
            var rxOk = !isNaN(rx);
            var tx = !isNaN(txRaw) ? txRaw : rx;

            if (!rxOk || !inSupportedBand(rx)) return null;
            if (Math.round(rx * 1000) % 5 !== 0) return null;

            var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
            var tonoNum = parseFloat(tonoRaw);
            var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) {{ return Math.abs(t - tonoNum) < 0.05; }});
            var hasTone = tonoRaw !== '' && isValidTone;
            var toneMode = hasTone ? 'TONE' : 'OFF';
            var ctcssFreq = hasTone ? tonoNum.toFixed(1) + ' Hz' : '88.5 Hz';

            var mode = mapMode(r.banda);
            var isAM = mode === 'AM';

            var normalizeText = function (s) {{
              return String(s)
                .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
                .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
                .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
                .toUpperCase();
            }};

            var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 16) : '';
            var comment = r.nombre != null ? normalizeText(String(r.nombre)) : '';

            var offset = rxOk ? parseFloat(Math.abs(tx - rx).toFixed(6)).toString() : '0';

            var fmtFreq = function (f) {{ return parseFloat(f.toFixed(6)).toString(); }};

            var cols = [
              channel++,
              'OFF',
              rxOk ? fmtFreq(rx) : '',
              rxOk ? fmtFreq(tx) : '',
              offset,
              rxOk ? (tx > rx ? '+RPT' : tx < rx ? '-RPT' : 'OFF') : 'OFF',
              'ON',
              mode,
              mode,
              'ON',
              esc(name),
              toneMode,
              ctcssFreq,
              '023',
              'RX Normal TX Normal',
              '1600 Hz',
              isAM ? '-' : 'RX 00',
              isAM ? '-' : 'TX 00',
              'L2 (1W)',
              'OFF',
              'ON',
              '12.5KHz'
            ].concat(flags).concat([esc(comment), 0]);
            return cols.join(',');
          }}).filter(function (line) {{ return line !== null; }});

          while (dataRows.length < 900) {{
            var ch = dataRows.length + 1;
            var emptyRow = new Array(54).fill('');
            emptyRow[0] = ch;
            emptyRow[53] = 0;
            dataRows.push(emptyRow.join(','));
          }}

          /* No header row — Yaesu ADMS format starts directly with data, fixed 899 rows */
          var csv = dataRows.join('\\r\\n');
          var blob = new Blob([csv], {{ type: 'text/csv;charset=utf-8' }});
          var a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = buildFT5DRFilename(criteria);
          a.click();
          URL.revokeObjectURL(a.href);
        }}
        """)


def generate_ftm150_mapper(num_cols: int) -> str:
    return textwrap.dedent(f"""\
        /**
         * Yaesu FTM-150 ADMS CSV exporter for Radiomap repeater data.
         * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
         * Format: Yaesu ADMS compatible CSV — no header row, {num_cols} columns per row.
         *
         * Column layout (from reference.csv):
         *   0:channel  1:rx_freq  2:tx_freq  3:offset(|tx-rx|)  4:offset_dir
         *   5:mode  6:name(8)  7:tone_mode  8:ctcss_freq  9:dcs_code
         *   10:bell  11:power  12:pager  13:bclo  14:step
         *   15:att  16:squelch  17:comment  18:0
         *
         * Exposes:
         *   exportFTM150(rows, criteria)  — triggers browser download
         *   buildFTM150Filename(criteria) — returns filename string
         */

        function buildFTM150Filename(criteria) {{
          var date = new Date().toISOString().slice(0, 10);
          var parts = ['radiomap', 'ftm150'];
          var sanitize = function (s) {{
            return String(s).replace(/\\s+/g, '-').replace(/[^a-zA-Z0-9\\-\\u00e1\\u00e9\\u00ed\\u00f3\\u00fa\\u00f1]/g, '').toLowerCase().slice(0, 30);
          }};
          if (criteria) {{
            if (criteria.context === 'neighbors') {{
              parts.push('nodos-cercanos');
              if (criteria.signal) parts.push(sanitize(criteria.signal));
            }}
            if (criteria.nearMe) parts.push('cerca-de-mi');
            var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
            bandas.forEach(function (b) {{ if (b) parts.push(String(b).toLowerCase()); }});
            var types = criteria.types || [];
            if (types.indexOf('echolink') >= 0) parts.push('echolink');
            if (types.indexOf('dmr') >= 0) parts.push('dmr');
            if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
            if (types.indexOf('atc') >= 0) parts.push('atc');
            if (types.indexOf('fire') >= 0) parts.push('bomberos');
            if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
            if (types.indexOf('sea') >= 0) parts.push('maritimo');
            var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
            conferences.forEach(function (c) {{ if (c) parts.push('conferencia-' + sanitize(c)); }});
            var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
            regions.forEach(function (reg) {{ var r = sanitize(reg); if (r) parts.push('region-' + r); }});
            var search = criteria.search != null ? criteria.search : '';
            if (search && String(search).trim()) {{
              var q = sanitize(String(search).trim()).slice(0, 20);
              if (q) parts.push('busqueda-' + q);
            }}
          }}
          parts.push(date);
          return parts.join('-') + '.csv';
        }}

        function exportFTM150(rows, criteria) {{
          var esc = function (v) {{
            if (v == null || v === '') return '';
            var s = '' + v;
            if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\\n') >= 0) {{
              return '"' + s.replace(/"/g, '""') + '"';
            }}
            return s;
          }};

          var mapMode = function (banda) {{
            if (!banda) return 'FM';
            var b = String(banda).toUpperCase();
            if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
            return 'FM';
          }};

          /* Yaesu FTM-150 supported bands: VHF 108-174 MHz, UHF 420-470 MHz */
          var inSupportedBand = function (f) {{
            return (f >= 108 && f <= 174) || (f >= 420 && f <= 470);
          }};

          /* Standard CTCSS tones (EIA) */
          var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
            100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
            146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
            218.1,225.7,233.6,241.8,250.3];

          var normalizeText = function (s) {{
            return String(s)
              .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
              .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
              .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
              .toUpperCase();
          }};

          var channel = 1;
          var dataRows = rows.map(function (r) {{
            if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
                (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {{
              return null;
            }}

            var rx = parseFloat(r.rx);
            var txRaw = parseFloat(r.tx);
            var rxOk = !isNaN(rx);
            var tx = !isNaN(txRaw) ? txRaw : rx;

            if (!rxOk || !inSupportedBand(rx)) return null;
            if (Math.round(rx * 1000) % 5 !== 0) return null;

            var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
            var tonoNum = parseFloat(tonoRaw);
            var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) {{ return Math.abs(t - tonoNum) < 0.05; }});
            var hasTone = tonoRaw !== '' && isValidTone;
            var toneMode = hasTone ? 'TONE' : 'OFF';
            var ctcssFreq = hasTone ? tonoNum.toFixed(1) + ' Hz' : '100.0 Hz';

            var mode = mapMode(r.banda);

            var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 8) : '';
            var comment = r.nombre != null ? normalizeText(String(r.nombre)) : '';

            var fmtFreq = function (f) {{ return parseFloat(f.toFixed(5)).toString(); }};
            var offset = parseFloat(Math.abs(tx - rx).toFixed(2)).toString();
            var offsetDir = rxOk ? (tx > rx ? '+RPT' : tx < rx ? '-RPT' : 'OFF') : 'OFF';
            var step = rx < 300 ? '5.0KHz' : '25.0KHz';

            var cols = [
              channel++,
              rxOk ? fmtFreq(rx) : '',
              rxOk ? fmtFreq(tx) : '',
              offset,
              offsetDir,
              mode,
              esc(name),
              toneMode,
              ctcssFreq,
              '023',
              '1500 Hz',
              'HIGH',
              'OFF',
              'YES',
              step,
              'OFF',
              'OFF',
              esc(comment),
              0
            ];
            return cols.join(',');
          }}).filter(function (line) {{ return line !== null; }});

          while (dataRows.length < 1000) {{
            var ch = dataRows.length + 1;
            var emptyRow = new Array(19).fill('');
            emptyRow[0] = ch;
            emptyRow[18] = 0;
            dataRows.push(emptyRow.join(','));
          }}

          /* No header row — Yaesu ADMS format starts directly with data, fixed 1000 rows */
          var csv = dataRows.join('\\r\\n');
          var blob = new Blob([csv], {{ type: 'text/csv;charset=utf-8' }});
          var a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = buildFTM150Filename(criteria);
          a.click();
          URL.revokeObjectURL(a.href);
        }}
        """)


def generate_opengd77_mapper(headers: list[str]) -> str:
    header_str = ",".join(headers)
    num_cols = len(headers)
    return textwrap.dedent(f"""\
        /**
         * OpenGD77 CPS CSV exporter for Radiomap repeater data.
         * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
         * Format: OpenGD77 CPS channel import CSV — with header row, {num_cols} columns per row.
         * Columns: {header_str}
         *
         * Supports both Analogue and Digital (DMR) channels.
         * DMR fields used: r.color (Colour Code), r.slot (Timeslot).
         *
         * Exposes:
         *   exportOpenGD77(rows, criteria)  — triggers browser download
         *   buildOpenGD77Filename(criteria) — returns filename string
         */

        function buildOpenGD77Filename(criteria) {{
          var date = new Date().toISOString().slice(0, 10);
          var parts = ['radiomap', 'opengd77'];
          var sanitize = function (s) {{
            return String(s).replace(/\\s+/g, '-').replace(/[^a-zA-Z0-9\\-\\u00e1\\u00e9\\u00ed\\u00f3\\u00fa\\u00f1]/g, '').toLowerCase().slice(0, 30);
          }};
          if (criteria) {{
            if (criteria.context === 'neighbors') {{
              parts.push('nodos-cercanos');
              if (criteria.signal) parts.push(sanitize(criteria.signal));
            }}
            if (criteria.nearMe) parts.push('cerca-de-mi');
            var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
            bandas.forEach(function (b) {{ if (b) parts.push(String(b).toLowerCase()); }});
            var types = criteria.types || [];
            if (types.indexOf('echolink') >= 0) parts.push('echolink');
            if (types.indexOf('dmr') >= 0) parts.push('dmr');
            if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
            if (types.indexOf('atc') >= 0) parts.push('atc');
            if (types.indexOf('fire') >= 0) parts.push('bomberos');
            if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
            if (types.indexOf('sea') >= 0) parts.push('maritimo');
            var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
            conferences.forEach(function (c) {{ if (c) parts.push('conferencia-' + sanitize(c)); }});
            var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
            regions.forEach(function (reg) {{ var r = sanitize(reg); if (r) parts.push('region-' + r); }});
            var search = criteria.search != null ? criteria.search : '';
            if (search && String(search).trim()) {{
              var q = sanitize(String(search).trim()).slice(0, 20);
              if (q) parts.push('busqueda-' + q);
            }}
          }}
          parts.push(date);
          return parts.join('-') + '.csv';
        }}

        function exportOpenGD77(rows, criteria) {{
          var HEADER = '{header_str}';

          var esc = function (v) {{
            if (v == null || v === '') return '';
            var s = '' + v;
            if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\\n') >= 0) {{
              return '"' + s.replace(/"/g, '""') + '"';
            }}
            return s;
          }};

          /* OpenGD77 supported bands: VHF 136-174 MHz, UHF 400-470 MHz */
          var inSupportedBand = function (f) {{
            return (f >= 136 && f <= 174) || (f >= 400 && f <= 470);
          }};

          /* Standard CTCSS tones (EIA) */
          var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
            100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
            146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
            218.1,225.7,233.6,241.8,250.3];

          var normalizeText = function (s) {{
            return String(s)
              .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
              .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
              .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
              .toUpperCase();
          }};

          var channel = 1;
          var dataRows = rows.map(function (r) {{
            var rx = parseFloat(r.rx);
            var txRaw = parseFloat(r.tx);
            var rxOk = !isNaN(rx);
            var tx = !isNaN(txRaw) ? txRaw : rx;

            if (!rxOk || !inSupportedBand(rx)) return null;

            var isDMR = r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
                (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0);

            var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 16) : '';
            var fmtFreq = function (f) {{ return f.toFixed(5); }};

            var cols;
            if (isDMR) {{
              var colorCode = (r.color != null && r.color !== '') ? String(r.color) : '1';
              var timeslot = (r.slot != null && r.slot !== '') ? String(r.slot) : '1';
              cols = [
                channel++, esc(name), 'Digital',
                rxOk ? fmtFreq(rx) : '', rxOk ? fmtFreq(tx) : '',
                '', colorCode, timeslot, '', '', '',
                'Off', 'Off', '', '', '',
                'Master', 'No', 'No', 'No', '0', 'Off', 'No', 'No', '', '0', '0', 'No'
              ];
            }} else {{
              var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
              var tonoNum = parseFloat(tonoRaw);
              var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) {{ return Math.abs(t - tonoNum) < 0.05; }});
              var hasTone = tonoRaw !== '' && isValidTone;
              var tone = hasTone ? tonoNum.toFixed(1) : '';
              cols = [
                channel++, esc(name), 'Analogue',
                rxOk ? fmtFreq(rx) : '', rxOk ? fmtFreq(tx) : '',
                '12.5', '', '', '', '', '',
                '', '', tone, tone, 'Disabled',
                'Master', 'No', 'No', 'No', '0', 'Off', 'No', 'No', '', '0', '0', 'No'
              ];
            }}
            return cols.join(',');
          }}).filter(function (line) {{ return line !== null; }});

          var csv = [HEADER].concat(dataRows).join('\\r\\n');
          var blob = new Blob([csv], {{ type: 'text/csv;charset=utf-8' }});
          var a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = buildOpenGD77Filename(criteria);
          a.click();
          URL.revokeObjectURL(a.href);
        }}
        """)


def generate_stub_mapper(fmt: str, headers: list[str]) -> str:
    col_comment = ", ".join(headers)
    fn_name = "export" + fmt.capitalize()
    return textwrap.dedent(f"""\
        /**
         * {fmt.upper()} exporter stub — generated by scripts/generate-exporter-mapper.py
         * Columns: {col_comment}
         * TODO: implement mapping logic for this format.
         */
        function {fn_name}(rows, criteria) {{
          console.warn('{fn_name}: not yet implemented');
        }}
        """)


def read_settings(folder: Path) -> dict:
    settings_path = folder / "settings.json"
    if settings_path.exists():
        with open(settings_path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def generate_registry(exporters: list[dict]) -> str:
    lines = ["/* Generated by scripts/generate-exporter-mapper.py — do not edit by hand. */",
             "window.RADIOMAP_EXPORTERS = ["]
    for i, meta in enumerate(exporters):
        parts = [
            f"id: '{meta['id']}'",
            f"label: '{meta['label']}'",
            f"fn: '{meta['fn']}'",
        ]
        if meta.get("url"):
            parts.append(f"url: '{meta['url']}'")
        comma = "," if i < len(exporters) - 1 else ""
        lines.append("  { " + ", ".join(parts) + " }" + comma)
    lines.append("];\n")
    return "\n".join(lines)


def main() -> None:
    if not EXPORTER_ROOT.is_dir():
        raise SystemExit(f"Exporter root not found: {EXPORTER_ROOT}")

    exporters: list[dict] = []

    for ref in sorted(EXPORTER_ROOT.glob("*/reference.csv")):
        fmt = ref.parent.name
        headers = read_headers(ref)
        if not headers:
            print(f"[SKIP] {fmt}: reference.csv has no headers")
            continue

        if fmt == "chirp":
            content = generate_chirp_mapper(headers)
        elif fmt == "ft5dr":
            content = generate_ft5dr_mapper(headers)
        elif fmt == "ftm150":
            content = generate_ftm150_mapper(len(headers))
        elif fmt == "opengd77":
            content = generate_opengd77_mapper(headers)
        else:
            content = generate_stub_mapper(fmt, headers)

        out_path = ref.parent / "mapper.js"
        out_path.write_text(content, encoding="utf-8")
        print(f"[OK]   {fmt}: wrote {out_path} ({len(headers)} columns)")

        settings = read_settings(ref.parent)
        exporters.append({
            "id": fmt,
            "label": settings.get("label", fmt.upper()),
            "fn": settings.get("fn", "export" + fmt.capitalize()),
            "url": settings.get("url", ""),
        })

    registry_path = EXPORTER_ROOT / "registry.js"
    registry_path.write_text(generate_registry(exporters), encoding="utf-8")
    print(f"[OK]   registry: wrote {registry_path} ({len(exporters)} exporter(s))")


if __name__ == "__main__":
    main()
